DimensionDev/Flare

shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/NodeInfoService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/model/Schema10.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/model/Schema11.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/model/Schema20.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/model/Schema21.kt
currently kmyblue and fedibird
=> add support for mastodon forks

shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/NodeInfoService.kt
=> add support for sharkey

app/src/main/java/dev/dimension/flare/ui/component/status/CommonStatusComponent.kt, app/src/main/java/dev/dimension/flare/ui/screen/status/StatusTranslatePresenter.kt, iosApp/iosApp/UI/Component/Status/CommonStatusComponent.swift, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/microblog/Paging.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiTimeline.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Mastodon.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> make content warning rich text

shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> only parsing emoji in username for misskey

app/src/main/java/dev/dimension/flare/ui/component/status/UiTimelineComponent.kt, app/src/main/res/values/strings.xml, iosApp/iosApp/UI/Component/Status/StatusRetweetHeaderComponent.swift, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/AccountApi.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/Notification.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiTimeline.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> fix notification api call

app/src/main/java/dev/dimension/flare/ui/icons/MisskeyIcon.kt
=> update misskey icon

app/src/main/java/dev/dimension/flare/ui/component/HtmlText.kt, app/src/main/java/dev/dimension/flare/ui/component/status/CommonStatusComponent.kt, shared/src/androidMain/kotlin/dev/dimension/flare/ui/render/UiRichText.android.kt
=> fix emoji only text not being displayed

app/src/main/java/dev/dimension/flare/ui/component/NetworkImage.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> fix misskey cancel reaction crash

app/src/main/java/dev/dimension/flare/ui/component/bottomSheetNavigation/DestinationStyleBottomSheet.kt, app/src/main/java/dev/dimension/flare/ui/component/status/CommonStatusComponent.kt, app/src/main/java/dev/dimension/flare/ui/screen/home/HomeScreen.kt, app/src/main/java/dev/dimension/flare/ui/screen/status/action/MisskeyReactionSheet.kt, gradle/libs.versions.toml, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/Note.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/User.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/UserLite.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiTimeline.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/status/action/MisskeyReactionPresenter.kt
=> fix misskey emoji does not show up

shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> fix misskey user name deeplink

app/src/main/java/dev/dimension/flare/ui/screen/compose/ComposeScreen.kt
=> fix compose input focus when cw is enable

app/src/main/java/dev/dimension/flare/ui/screen/list/ListScreen.kt
FAIcon and Text were overlapped in List Screen.
|before|after|
|:-:|:-:
|![flare_overlap_issue](https://github.com/user-attachments/assets/9c40b3c4-19d8-40e9-9621-7b84dd586ba8)|![flare_overlap_fixed](https://github.com/user-attachments/assets/b14fd035-99f1-44b4-b6b7-8b8f9faff6b9)|
=> Remove FAIcon and Text overlap in List Screen

shared/src/commonMain/kotlin/dev/dimension/flare/data/database/cache/mapper/Misskey.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
https://github.com/DimensionDev/Flare/pull/691#issuecomment-2618120146
I confirmed to work.
=> misskey only poll renote is quote

shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Mastodon.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> fix misskey and mastodon cannote reblog from user himself

shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Mastodon.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
Related to #703 
Direct/Specified can't boost/renote.
=> Exclude canReblog target Direct/Specifed

app/src/main/java/dev/dimension/flare/data/model/TabSettings.kt, app/src/main/java/dev/dimension/flare/ui/component/status/CommonStatusComponent.kt, app/src/main/java/dev/dimension/flare/ui/component/status/StatusActionButton.kt, iosApp/iosApp/UI/Page/Home/Components/Status/CommonTimelineStatusComponent.swift, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/microblog/StatusAction.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/microblog/StatusEvent.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/FavouriteTimelineRemoteMediator.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/home/misskey/MisskeyFavouriteTimelinePresenter.kt
=> add favourite support for misskey

app/src/main/java/dev/dimension/flare/ui/component/EmojiPicker.kt, app/src/main/java/dev/dimension/flare/ui/component/SearchBar.kt, app/src/main/java/dev/dimension/flare/ui/screen/compose/ComposeScreen.kt, app/src/main/java/dev/dimension/flare/ui/screen/status/action/MisskeyReactionSheet.kt, app/src/main/res/values/strings.xml, iosApp/iosApp/UI/Page/Compose/View/ComposeScreen.swift, iosApp/iosApp/UI/Status/MisskeyReactionSheet.swift, shared/src/commonMain/kotlin/dev/dimension/flare/common/ImmutableListWrapper.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/database/cache/CacaheDatabase.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/database/cache/dao/EmojiDao.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/database/cache/model/DbEmoji.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/mastodon/MastodonDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/microblog/ComposeConfig.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/repository/LocalFilterRepository.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/repository/SearchHistoryRepository.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiEmoji.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Mastodon.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/compose/ComposePresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/compose/EmojiHistoryPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/home/SearchHistoryPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/profile/ProfileNewPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/profile/ProfilePresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/settings/AccountsPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/settings/LocalFilterPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/settings/StoragePresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/status/action/MisskeyReactionPresenter.kt
=> Emoji picker rework

app/src/main/java/dev/dimension/flare/ui/component/EmojiPicker.kt
=> single line for emoji picker

app/src/main/java/dev/dimension/flare/ui/component/EmojiPicker.kt
=> fix emoji pick search

app/src/main/java/dev/dimension/flare/ui/screen/list/CreateListDialog.kt, app/src/main/java/dev/dimension/flare/ui/screen/list/EditListScreen.kt, app/src/main/java/dev/dimension/flare/ui/screen/list/ListScreen.kt, gradle/libs.versions.toml, shared/build.gradle.kts, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/bluesky/BlueskyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/bluesky/BlueskyService.kt
=> fix bluesky list state not being updated

app/src/main/java/dev/dimension/flare/data/model/TabSettings.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/ListTimelineRemoteMediator.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/SearchUserPagingSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/MisskeyService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/ListsApi.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/ListMembership.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/NotesUserListTimelineRequest.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/model/UsersListsListRequest.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt
=> add list support for misskey

app/src/main/java/dev/dimension/flare/ui/screen/status/action/AddReactionSheet.kt, iosApp/iosApp.xcodeproj/project.pbxproj, iosApp/iosApp/UI/Navigation/Route.swift, iosApp/iosApp/UI/Status/AddReactionSheet.swift, shared/src/appleMain/kotlin/dev/dimension/flare/common/AppDeepLink.apple.kt, shared/src/commonMain/kotlin/dev/dimension/flare/common/AppDeepLink.kt, shared/src/commonMain/kotlin/dev/dimension/flare/common/JSON.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/mastodon/MastodonDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/microblog/ReactionDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/microblog/StatusEvent.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/pleroma/PleromaDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/Ktorfit.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/mastodon/api/model/EmojiReaction.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/mastodon/api/model/PostStatus.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/mastodon/api/model/Status.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/mastodon/api/model/Visibility.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/NodeInfoService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/xqt/XQTService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiAccount.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiTimeline.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Mastodon.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/compose/ComposePresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/login/MastodonCallbackPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/login/ServiceSelectPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/status/action/AddReactionPresenter.kt
=> add support for Pleroma/Akkoma

app/src/main/java/dev/dimension/flare/ui/screen/status/action/MisskeyReportDialog.kt, desktopApp/src/main/kotlin/dev/dimension/flare/ui/screen/status/action/MisskeyReportDialog.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/status/action/MisskeyReportPresenter.kt
=> add comment to misskey report

shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/ui/component/src/androidMain/kotlin/dev/dimension/flare/ui/component/platform/PlatformCard.android.kt, shared/ui/component/src/commonMain/kotlin/dev/dimension/flare/ui/component/platform/PlatformCard.kt, shared/ui/component/src/commonMain/kotlin/dev/dimension/flare/ui/component/status/CommonStatusComponent.kt, shared/ui/component/src/jvmMain/kotlin/dev/dimension/flare/ui/component/platform/PlatformCard.jvm.kt
=> add highlight for status reaction

app/src/main/java/dev/dimension/flare/data/model/TabSettings.kt, app/src/main/java/dev/dimension/flare/ui/route/Route.kt, app/src/main/java/dev/dimension/flare/ui/route/Router.kt, app/src/main/java/dev/dimension/flare/ui/screen/bluesky/BlueskyFeedsScreen.kt, app/src/main/java/dev/dimension/flare/ui/screen/home/HomeScreen.kt, app/src/main/java/dev/dimension/flare/ui/screen/list/ListEntryBuilder.kt, app/src/main/java/dev/dimension/flare/ui/screen/misskey/AntennasListScreen.kt, app/src/main/java/dev/dimension/flare/ui/screen/misskey/MisskeyEntryBuilder.kt, app/src/main/java/dev/dimension/flare/ui/screen/settings/TabCustomizeScreen.kt, app/src/main/java/dev/dimension/flare/ui/theme/Theme.kt, app/src/main/res/values/strings.xml, shared/src/androidJvmMain/kotlin/dev/dimension/flare/data/model/TabSettings.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/AntennasListPagingSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/AntennasTimelineRemoteMediator.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/misskey/MisskeyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/MisskeyService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/misskey/api/AntennasApi.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiList.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Misskey.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/list/AntennasListPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/list/AntennasTimelinePresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/list/PinnableTimelineTabPresenter.kt
=> add misskey antenna support

app/src/main/java/dev/dimension/flare/ui/screen/serviceselect/ServiceSelectScreen.kt, app/src/main/res/values/strings.xml, gradle/libs.versions.toml, iosApp/iosApp/UI/Page/OAuth/ServiceSelectScreen.swift, settings.gradle.kts, shared/build.gradle.kts, shared/src/appleMain/kotlin/dev/dimension/flare/common/AppDeepLink.apple.kt, shared/src/commonMain/kotlin/dev/dimension/flare/common/AppDeepLink.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/database/cache/mapper/Bluesky.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/bluesky/BlueskyDataSource.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/datasource/bluesky/NotificationRemoteMediator.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/bluesky/BlueskyAuthPlugin.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/bluesky/BlueskyService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/UiAccount.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/model/mapper/Bluesky.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/login/BlueskyLoginPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/login/BlueskyOAuthLoginPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/login/ServiceSelectPresenter.kt
=> add oauth login support for bluesky

compose-ui/src/commonMain/composeResources/values/strings.xml, compose-ui/src/commonMain/kotlin/dev/dimension/flare/ui/screen/login/ServiceSelectionScreenContent.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/mastodon/api/InstanceResources.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/mastodon/api/model/InstanceInfoV1.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/nodeinfo/NodeInfoService.kt, shared/src/commonMain/kotlin/dev/dimension/flare/data/network/xqt/elonmusk114514/ElonMusk1145141919810.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/login/NodeInfoPresenter.kt, shared/src/commonMain/kotlin/dev/dimension/flare/ui/presenter/settings/GuestConfigPresenter.kt
=> change the way to detect server compatibility
